### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by LukasDrsman** [sharkdp/insect#209]
```
/usr/bin/insect -> /usr/lib/node_modules/insect/index.js

> insect@5.3.0 postinstall /usr/lib/node_modules/insect
> bower --allow-root install && npm run browserify && npm run copy

/usr/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at Configstore.get (/usr/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at new Configstore (/usr/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:45)
    at readCachedConfig (/usr/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.config/configstore/bower-github.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insect@5.3.0 postinstall: `bower --allow-root install && npm run browserify && npm run copy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insect@5.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-22T11_27_41_815Z-debug.log
```
npm version: 6.11.3

command used: `sudo npm install -g insect`

**Comment by sharkdp** [comment]
This could be related: https://github.com/bower/bower/issues/2262

**Comment by apandada1** [comment]
The comment at bower/bower#2262 does not help. I get the same error.

**Comment by sharkdp** [comment]
Any help would be greatly appreciated. I also can't seem to get it to work.

**Comment by sharkdp** [comment]
I did not find a way to fix this, but there is another way to install `insect` - as a user. Please see the updated install instructions in the README.
